# RuggedTrails Config
# Author: Yooogle (Joel DeSante)
# ------------------------------

# What are the odds of a block degrading?
probability: 0.0001

# Would you like to allow grass paths (Like the ones typically found in villages)
# More Info: https://minecraft.gamepedia.com/Grass_Path
enable_grass_paths: false

# Mudding occurs when it rains in minecraft. 
# Enabling this will allow grass paths to turn into dirt when walked on
enable_mudding: false

# Trails depending on gamemode
# aka. If a player is in a certain gamemode, will they be allowed to create trails?
enable_trails_in_survival: true
enable_trails_in_adventure: true
enable_trails_in_creative: false