# RuggedTrails 2
# The new, the improved, the functional!
#
# Also... CHECK THE DOCUMENTATION BEFORE CHANGING STUFF (ie. Ram Reducer)
# https://www.spigotmc.org/resources/rugged-trails.65192/
# https://github.com/JoelDesante/RuggedTrails

